### PR TITLE
Multi process support

### PR DESCRIPTION
**Pull request by fruitl00p**
In order to speed the actual analysis up a bit further phan has support for parralel processing.

This change includes support for this by building the image with `pcntl` support

### CODE REVIEW

**Comment by terinjokes** [comment]
Giving this a test.

**Comment by terinjokes** [comment]
Merged as d28a45c882e98718f20f1b396285d3f1b9ddc5c3. Releases are running now.

**Comment by fruitl00p** [comment]
Cool, thnx

**Comment by terinjokes** [comment]
Releases 0.2 (likely to be the last release of this) to 0.5, plus the current master, have been pushed to Docker Hub.

**Pull request closed without merging**
